### ISSUE TITLE
memory leak in Pl_Flate::write, indirectly called by qpdf_read_memory

### ISSUE THREAD

**Issue by hannob** [qpdf/qpdf#148]
The attached file, when passed as a buffer to qpdf_read_memory, will cause a memory leak.
[qpdf-leak.zip](https://github.com/qpdf/qpdf/files/1246685/qpdf-leak.zip)

Apart from that it's generally useful to fix memory leaks, fixing such bugs would be helpful in making it possible to fuzz qpdf with libfuzzer, which is an extremely effective fuzzing tool.

Here's the output from address sanitizer:
```
==8468==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 7160 byte(s) in 1 object(s) allocated from:
    #0 0x4d6978 in __interceptor_malloc (/r/qpdf/libfuzzer-qpdf+0x4d6978)
    #1 0x7ff0b4db444c in inflateInit2_ (/lib64/libz.so.1+0x844c)
    #2 0x76f1c3 in Pl_Flate::write(unsigned char*, unsigned long) (/r/qpdf/libfuzzer-qpdf+0x76f1c3)
    #3 0x56ee29 in QPDF::pipeStreamData(int, int, long long, unsigned long, QPDFObjectHandle, Pipeline*, bool) (/r/qpdf/libfuzzer-qpdf+0x56ee29)
    #4 0x68eb1c in QPDF::Pipe::pipeStreamData(QPDF*, int, int, long long, unsigned long, QPDFObjectHandle, Pipeline*, bool) (/r/qpdf/libfuzzer-qpdf+0x68eb1c)
    #5 0x6850d8 in QPDF_Stream::pipeStreamData(Pipeline*, unsigned long, qpdf_stream_decode_level_e, bool) (/r/qpdf/libfuzzer-qpdf+0x6850d8)
    #6 0x680640 in QPDF_Stream::getStreamData(qpdf_stream_decode_level_e) (/r/qpdf/libfuzzer-qpdf+0x680640)
    #7 0x5ca2b2 in QPDFObjectHandle::getStreamData(qpdf_stream_decode_level_e) (/r/qpdf/libfuzzer-qpdf+0x5ca2b2)
    #8 0x552b72 in QPDF::processXRefStream(long long, QPDFObjectHandle&) (/r/qpdf/libfuzzer-qpdf+0x552b72)
    #9 0x5451d2 in QPDF::read_xrefStream(long long) (/r/qpdf/libfuzzer-qpdf+0x5451d2)
    #10 0x52ee17 in QPDF::read_xref(long long) (/r/qpdf/libfuzzer-qpdf+0x52ee17)
    #11 0x52b691 in QPDF::parse(char const*) (/r/qpdf/libfuzzer-qpdf+0x52b691)
    #12 0x529293 in QPDF::processInputSource(PointerHolder<InputSource>, char const*) (/r/qpdf/libfuzzer-qpdf+0x529293)
    #13 0x529911 in QPDF::processMemoryFile(char const*, char const*, unsigned long, char const*) (/r/qpdf/libfuzzer-qpdf+0x529911)
    #14 0x5179d1 in call_read_memory(_qpdf_data*) (/r/qpdf/libfuzzer-qpdf+0x5179d1)
    #15 0x516393 in trap_errors(_qpdf_data*, void (*)(_qpdf_data*)) (/r/qpdf/libfuzzer-qpdf+0x516393)
    #16 0x517856 in qpdf_read_memory (/r/qpdf/libfuzzer-qpdf+0x517856)
    #17 0x513fb9 in LLVMFuzzerTestOneInput (/r/qpdf/libfuzzer-qpdf+0x513fb9)
    #18 0x7b6d1a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /mnt/ram/./Fuzzer/FuzzerLoop.cpp:494:13
    #19 0x7ace11 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /mnt/ram/./Fuzzer/FuzzerDriver.cpp:273:6
    #20 0x7b0e1b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /mnt/ram/./Fuzzer/FuzzerDriver.cpp:690:9
    #21 0x7acb80 in main /mnt/ram/./Fuzzer/FuzzerMain.cpp:20:10
    #22 0x7ff0b3acd4f0 in __libc_start_main (/lib64/libc.so.6+0x204f0)

SUMMARY: AddressSanitizer: 7160 byte(s) leaked in 1 allocation(s).

**Comment by jberkenbilt** [comment]
Yes, I am able to reproduce this as well. There appears to be an actual potential for buffer overrun. I will carefully check all code paths that lead to iterate_rc4 and make sure this can't happen.

**Comment by jberkenbilt** [comment]
I posted an earlier comment here that was supposed to be for a different issue (the rc4) one. However, I am able to reproduce this, and it doesn't have anything to do with read_memory. Just a regular old qpdf --check leaks 7160 bytes.
